### PR TITLE
Protocol: fix emitOnCapturedContext.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/tmds/Tmds.DBus/issues/191.

cc @madewokherd

### CODE REVIEW

**Comment by tmds** [comment]
@madewokherd is there something you can try this out with?
And feel free to take a look at the PR and add any comments you may have.

**Comment by madewokherd** [comment]
Thanks, I'll try to test this tomorrow.

**Comment by madewokherd** [comment]
Yep, this fixes my use case.

**Comment by tmds** [comment]
This is fixed in 0.15.0 which is now on nuget.org.

**Pull request merged**
