### PR TITLE
Make SignatureReader public

### PR DESCRIPTION
**Pull request by affederaffe**
The `SignatureReader` is needed to parse variants in the source generator, see https://github.com/affederaffe/Tmds.DBus.SourceGenerator/blob/3e76fbf5be03b8e1360e74b8878c541d9de808cd/Tmds.DBus.SourceGenerator/DBusSourceGenerator.Classes.cs#L240

### CODE REVIEW

**Comment by tmds** [comment]
@affederaffe can you make `public` only the members you need (ctor, and `TryRead`), and make the rest `internal`?

**Comment by tmds** [comment]
The 'Transform' method too.

**Comment by tmds** [comment]
To keep it internal, you need to add back the 'InternalsVisibleTo' attribute.

**Comment by affederaffe** [comment]
Done, sorry for the fuss

**Comment by tmds** [comment]
No problem. I'll be making a new release to nuget.org with this included in a moment.

**Comment by tmds** [comment]
Tmds.DBus.Protocol 0.13.0 is on nuget.org.

I'm looking forward to try out your source generator.

**Pull request merged**
