### PR TITLE
Protocol: add support for implementing DBus.Introspectable.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/tmds/Tmds.DBus/issues/220.

### CODE REVIEW

**Comment by tmds** [comment]
@jmacato @affederaffe this provides Introspectable support for the Protocol library.

As a library user, you can look at the `docs/protocol.md` file on how to use this.

Feel free to review the PR and provide feedback.

I'll merge this some time next week, and then you can try this out further using a NuGet package from the CI feed.
If this is working well for you, I'll make a new release to nuget.org.

**Comment by tmds** [comment]
I'm going to merge this already. The PR comes with many tests, so it is more interesting to have it on the CI feed where you can consume it easily.

When you change to this build, this will happen: the library will handle the `Peer` interface, and the `Introspectable` interface without needing any changes. If you use a tool like D-Feet, you'll see the objects appear.

To have the interfaces show up that an `IMethodHandler` implements, the handler must include the following in its `HandleMethodAsync`:

```cs
        if (context.IsDBusIntrospectRequest)
        {
            context.ReplyIntrospectXml([ ... ]);
            return default;
        }
```

The argument is an `ReadOnlySpan<ReadOnlyMemory<byte>> interfaceXmls` which enables passing a list of UTF-8 encoded interface xmls.

There's no need to pass `Peer` or `Introspectable`, this gets handled by the library.

`IMethodHandlers` that implement the `Properties` interface, can pass `IntrospectionXml.DBusProperties` for that.

The library takes care of adding the child names in the response.

**Comment by tmds** [comment]
This is part of 0.16.0 which was just published to nuget.org.

**Comment by affederaffe** [comment]
Thanks, that seems to be a good solution.
Tmds.DBus.SourceGenerator now exposes this API with ObserverFlags.None as the default.

**Pull request merged**
