### PR TITLE
Don't try to call delegates with "this" as an argument.

### PR DESCRIPTION
**Pull request by madewokherd**
For https://github.com/tmds/Tmds.DBus/issues/155.

### CODE REVIEW

**Comment by madewokherd** [comment]
MessageReader methods could also be changed to static, but that's a more invasive change than I'd be comfortable attempting without being asked to.

**Comment by tmds** [comment]
Thanks @madewokherd!

Do we need to make a similar change for the `MessageWriter`?

Can you write a reproducer for the problem you see with Mono, and file it on mono/mono or dotnet/runtime repo?

**Comment by madewokherd** [comment]
> Do we need to make a similar change for the `MessageWriter`?

I think so, but it wasn't obvious to me how to test that.

> Can you write a reproducer for the problem you see with Mono, and file it on mono/mono or dotnet/runtime repo?

I'll try, thank you for the reminder.

**Comment by madewokherd** [comment]
I haven't been able to reproduce the crash in Mono with a small test case, so it seems there's something else going on here.

**Comment by madewokherd** [comment]
Actually, I don't understand this code: https://github.com/tmds/Tmds.DBus/blob/main/src/Tmds.DBus/CodeGen/DBusObjectProxyTypeBuilder.cs#L147

You appear to be calling the delegate constructor with null and a function pointer, but none of the documented constructors expect a function pointer. How is this meant to work?

**Comment by madewokherd** [comment]
I see, specific delegate types have a constructor taking an object instance and an IntPtr, not sure if I can test this from C#.

**Comment by madewokherd** [comment]
I tried modifying my testcase to call the delegate constructor through reflection, and that still didn't crash. I used `MethodInfo.RuntimeHandle.GetFunctionPointer()` to obtain the pointer to pass to the delegate constructor. Although C# now has a feature that makes using ldftn possible, it won't let me do what the generated code does:
```
/home/meh/junk/delegate-this-argument.cs(29,46): error CS8759: Cannot create a function pointer for 'DelegateThisArgumentTest.InstanceMethod<T>()' because it is not a static method
```

Changing the code generator in Tmds.DBus to call CreateReadMethodDelegate does work around the issue.

**Comment by madewokherd** [comment]
Looking at ECMA-335's description of newobj and II.14.6.1, this usage does seem to be out-of-spec. Even though MethodInfo.CreateDelegate seems to work more reliably, it's not clear to me whether that's supposed to work either, though Mono has a test that does something similar: https://github.com/mono/mono/blob/main/mono/tests/delegate10.cs

Mono also has a test for delegate creation like this, but it doesn't seem to call the resulting delegates: https://github.com/mono/mono/blob/main/mono/tests/delegate-with-null-target.il

**Comment by madewokherd** [comment]
Modifying [delegate-with-null-target.il](https://github.com/mono/mono/blob/main/mono/tests/delegate-with-null-target.il) to call Invoke also does not produce a crash. So while I've found a couple of work-arounds, I still don't understand why this is broken, nor do I have a path to creating a small testcase.

**Comment by tmds** [comment]
With this change, CI is failing: https://github.com/tmds/Tmds.DBus/runs/6286061576?check_suite_focus=true.

**Comment by madewokherd** [comment]
Maybe I can go back and fix this error, but I think I need to get the test suite running locally and properly understand the Mono bug before I can be sure of any changes. I'll get back to you on this.

**Pull request closed without merging**
